### PR TITLE
Add Docteur Gab's with test

### LINKED ISSUE #279: Add the beer : Docteur Gabs + tests
Let's add a beer in the code.

### PR DESCRIPTION
**Pull request by AllemanoEn**
Closes #279

### CODE REVIEW

**Comment by wasadigi** [comment]
Can you please submit 1 PR for every beer? Here, I have both beers (you probably did not move back to master branch before creating the Dr Gabs branch). Thanks!

**Comment by wasadigi** [comment]
Let's look carefully. If we look at the number of modified files, we see 2 so that looks promising. However, if we look closely at the commits, we see that PrixGarantie files have been removed (they were there, because this branch was created of PrixGarantie). So if I merge, PrixGarantie will disappear from the codebase. I see 2 options, one safe and one that requires more care. Safe: create a new branch from master, get the DrGabs files (use git checkout -- for that) and submit a new PR. Rewrite the history of this branch (which after you use the correct git commands will require you to do a force push). But I advise to use force push only if you know very well what you are doing.

**Comment by AllemanoEn** [comment]
Should I close this PR and delete my fb-dg ?

**Comment by wasadigi** [comment]
Yes, I think it's better.

**Pull request closed without merging**
